---

- hosts: local
  gather_facts: true
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.0.0-p253
  roles:
    - local_system
    - local_pg
    - local_npm
    - local_project
